name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test:
    name: 'Playwright Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        
      - name: Run Playwright tests
        run: npx playwright test
        
      - name: Check report directory
        run: |
          ls -la
          if [ -d "playwright-report" ]; then
            echo "Report directory exists"
            ls -la playwright-report/
          else
            echo "Report directory does not exist"
            mkdir -p playwright-report
            echo "Empty report directory created for artifact upload"
            echo "No tests were executed" > playwright-report/index.html
          fi
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 30